title: Smart Filter
description: This repository aims to create smart filters, majorly for selfies.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman
site_url: https://karan469.github.io/Smart-Filter/

gems:
  - jekyll-mentions
